src/docs/pages/guide/commitcode/index.vue
src/docs/pages/guide/usage/index.vue

1. Error spelling of 'morning' at /guide/usage
2. Error spelling at /guide/commitcode

fix error spelling of document

---

src/docs/pages/component/dropdown/index.vue
src/docs/pages/component/tip/index.vue
src/docs/pages/lab/index.vue
src/lib/components/dropdown/index.less
src/lib/components/dropdown/index.vue
src/lib/components/tip/index.vue
src/lib/utils/TipManager.js
src/lib/utils/TriggerManager.js

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
- `ui-dropdown`支持右键触发
- `ui-dropdown`和`ui-tip`的弹出框遇到边界会自动调整位置，使内容在窗口内
- `ui-tip`新增`auto-reverse`配置，当小提示超出窗口时允许反转方向

close #200

---

src/lib/components/imagemap/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复`ui-imagemap`的一个问题(custom validator check failed for prop "color")

fixed #206 ui-imagemap bug

---

src/lib/components/datepicker/index.less

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复`ui-datepicker`中的一个样式问题

fixed #217 ui-datepicker style bug

---

src/docs/pages/component/datepicker/index.vue
src/docs/pages/component/datetimepicker/index.vue
src/docs/pages/component/timepicker/index.vue
src/lib/components/datepicker/index.less
src/lib/components/datepicker/index.vue
src/lib/components/datetimepicker/index.vue
src/lib/components/timepicker/index.less
src/lib/components/timepicker/index.vue

__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
`ui-timepicker`、`ui-datepicker`、`ui-datetimepicker`新增`separator-type`配置

close #223 add separator-type config

---

README.md
src/docs/pages/component/select/index.vue
src/docs/tpl.html
src/lib/components/dropdown/index.less
src/lib/components/dropdown/index.vue
src/lib/components/private-datepicker/index.less
src/lib/components/private-timepicker/index.less
src/lib/components/select/index.vue
src/lib/utils/TipManager.js

__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复`ui-dropdown`和`ui-select`等有弹框的组件导致父容器出现竖向滚动条

fixed #227

---

src/lib/components/imagemap/index.vue

__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复`ui-imagemap`新增的热区自定义数据为`undefined`

fixed #237 the new zone custom data is undefined(ui-imagemap)

---

src/docs/pages/guide/logs/index.vue
src/docs/pages/lab/index.vue
src/lib/components/select/index.less
src/lib/components/select/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

fixed #252 ui-select itemlist hidden when use separate-emit config

---

src/docs/pages/component/select/index.vue
src/docs/pages/guide/config/index.vue
src/lib/components/select/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #251 ui-select add list-width config

---

src/docs/pages/component/upload/index.vue
src/lib/components/upload/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #261 update ui-upload validate

---

src/docs/pages/guide/morning/index.vue
src/docs/pages/lab/index.vue
src/lib/components/imagemap/index.vue
src/lib/index.js

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复`ui-imagemap`的值用`getGroup`方式取值时可能出现错误的问题

fixed #272 ui-imagemap getGroup value bug

---

src/lib/components/calendar/index.less
src/lib/components/calendar/index.vue
src/lib/components/private-datepicker/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #279 ui-datepicker highlight today

---

src/docs/common/menu.js
src/lib/components/formgroup/index.less

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
optimization formgroup font size

close #323 optimization formgroup font size

---

src/lib/components/select/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
separate-emit config error : removeEventListener of null

fixed #331 separate-emit config error : removeEventListener of null

---

src/docs/pages/lab/index.vue
src/lib/components/datepicker/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复`ui-datetimepicker`和`ui-datepicker`开启`is-range`配置后弹窗错位的问题

fixed #339 ui-datetimepicker tip offset bug

---

.circleci/config.yml
src/lib/components/datepicker/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复`ui-datepicker`和`ui-datetimepicker`在选中特定日期范围时显示区间错误的问题

fixed #275 ui-datepicker range style bug

---

src/lib/components/select/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复`ui-select`高性能模式下拉列表高度计算错误的问题

fixed #320 ui-selelct item height bug

---

src/lib/components/dialog/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复`ui-dialog`同步调用`toggle(true)`和`toggle(false)`时，窗口不会关闭的问题

fixed #402 ui-dialog toggle true and false immediately bug

---

CHANGELOG.md
src/docs/pages/guide/logs/index.vue
src/lib/common/color.less

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复边框和背景配色类无效的问题

fixed #455 border and bg color bug

---

src/docs/common/common.less
src/docs/pages/component/select/index.vue
src/lib/components/select/index.less
src/lib/components/select/index.vue
src/lib/components/texteditor/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
`ui-select`的选项内容现在仅支持HTML

close #462 ui-select support vue component

---

src/docs/pages/guide/logs/index.vue
src/docs/pages/guide/versionplan/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
更新Morning UI Roadmap

close #468 update roadmap

---

README.md

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
add browserstack logo

close #489 add browserstack logo

---

src/lib/components/imagemap/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复`ui-imagemap`在某些情况下缩放值会调整为`0%`的问题

fixed #493 ui-imagemap bug

---

src/docs/common/DocBody.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
修复在线演示中Morning UI版本可能不正确的问题

close #580 fixed live demo js and css problem

---

src/docs/common/DocBody.vue
src/docs/pages/component/tree/index.vue
src/lib/components/breadcrumbs/index.vue
src/lib/components/private-tree/index.less
src/lib/components/tree/index.less
src/lib/components/tree/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
- 所有表单的`value-change`事件支持`value`参数，可用于获取表单值
- `ui-tree`新增`block-leaf`配置，可用于展示块状的子节点
- 现在`ui-breadcrumbs`不会在组件初始化时被触发
- 修复`ui-tree`的一个图标对齐的问题

close #623 quick update

---

src/docs/pages/component/table/index.vue
src/lib/components/table/index.vue
src/lib/components/table/normal-table.vue
src/lib/components/table/title-table.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #629 quick update

---

src/docs/pages/component/table/index.vue
src/docs/pages/guide/custom/index.vue
src/lib/components/alert/index.less
src/lib/components/grid/index.less
src/lib/components/table/index.vue
src/lib/components/table/normal-table.vue
src/lib/components/table/title-table.vue
src/lib/styles/var.less
src/lib/utils/TipManager.js

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
- `ui-table`新增`setCheckedRows()`方法
- `ui-table`中的栅格间距支持自定义
- 优化`ui-alert`组件中的文本颜色

close #638 quick update

---

src/docs/pages/component/grid/index.vue
src/lib/components/grid/index.less

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #642 quick update

---

src/docs/pages/component/table/index.vue
src/lib/components/table/normal-table.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
quick update

close #662 0.12.28 quick update

---

src/docs/pages/component/table/index.vue
src/lib/components/table/normal-table.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #668 hotfix

---

src/docs/pages/component/datepicker/index.vue
src/docs/pages/component/datetimepicker/index.vue
src/docs/pages/component/timepicker/index.vue
src/lib/components/datepicker/index.vue
src/lib/components/datetimepicker/index.vue
src/lib/components/pagination/index.vue
src/lib/components/private-datepicker/index.vue
src/lib/components/private-timepicker/index.vue
src/lib/components/timepicker/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #674

---

src/docs/pages/component/calendar/index.vue
src/docs/pages/component/datepicker/index.vue
src/lib/components/calendar/index.less
src/lib/components/calendar/index.vue
src/lib/components/datepicker/index.vue
src/lib/components/pagination/index.vue
src/lib/components/private-datepicker/index.less
src/lib/components/private-datepicker/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #667 0.12.35 quick update

---

src/lib/components/cascader/index.vue
src/lib/components/radio/index.vue
src/lib/components/tab/index.less
src/lib/components/table/index.less
src/lib/components/table/normal-table.vue
src/lib/components/table/title-table.vue
src/lib/components/texteditor/index.less
src/lib/components/texteditor/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #734 quick update

---

src/docs/pages/component/slider/index.vue
src/lib/components/mindmap/index.vue
src/lib/components/select/index.vue
src/lib/components/slider/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #753 quick update

---

src/docs/pages/component/mindmap/index.vue
src/lib/components/mindmap/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #761 quick update

---

src/lib/components/imagemap/index.vue

首先感谢你的贡献！
__检查清单__
如果这是一次问题修复：
如果这是一个新功能或改进：
__说明__
简洁清晰的说明...

close #775
